'''
#封装添加调整费用模块
'''

from selenium import webdriver
from PageObject.AdustmentFeePage import *
from toolKit.log import *

def addAdustmentFeeModule(driver, ChooseMerchantDate='', SearchContract='', SearchAccount='', ClickFeeSear='', ClickCurrAdjustment1=''):
    driver.implicitly_wait(5)
    afa = AdustmentFeeAdd(driver)
    afa.financialManagement().click()
    logger.info(u'点击账务管理')
    afa.AdustmentFeeMangment().click()
    logger.info(u'点击调整费用')
    afa.AdustmentFeeMaintain().click()
    driver.switch_to.frame(afa.AdustmentFramList())
    logger.info(u'切换到添加调整费用界面的框架')
    time.sleep(4)
    afa.CliAdustmentAddBut().click()
    logger.info(u'点击添加调整费用按钮')
    driver.switch_to.default_content()
    time.sleep(1)
    driver.switch_to.frame(afa.AdustmentAdcover())
    # logger.info(u'切换到添加调整费用内框架')
    # time.sleep(1)
    # afa.MallBox().click()
    # afa.ChooseMallData().click()
    # logger.info(u'选择购物中心数据')
    time.sleep(1)
    afa.MerchantBox().click()
    afa.ChooseMerchantDate().send_keys(ChooseMerchantDate)
    logger.info(u'输入商户数据：%s' %ChooseMerchantDate)
    afa.ClikcMerSearBut().click()
    time.sleep(1)
    afa.MerchantResult().click()
    afa.ClickContractBox().click()
    afa.SearchContract().send_keys(SearchContract)
    logger.info(u'输入合同号数据：%s' % SearchContract)
    afa.ClickContractSearBut().click()
    time.sleep(1)
    afa.ClickContractResult().click()
    time.sleep(1)
    afa.ClickSettGroupBox().click()
    afa.ChooseGroupInfo().click()
    time.sleep(1)
    afa.AccoutBox().click()
    afa.AccoutSearBox().click()
    afa.SearchAccount().send_keys(SearchAccount)
    logger.info(u'输入合同号数据：%s' % SearchAccount)
    afa.SearchAccountBut().click()
    afa.ClickAccountResu().click()
    time.sleep(1)
    afa.ClickAddFeeInfo().click()
    time.sleep(1)
    afa.ClickAddFeeBox().click()
    afa.ClickFeePBox1().click()
    time.sleep(2)
    afa.ClickFeeSear().send_keys(ClickFeeSear)
    logger.info(u'当前选择费用项目是：%s' % ClickFeeSear)
    time.sleep(1)
    afa.ClickSFeeSearBut().click()
    afa.ClickSFeeResu().click()
    time.sleep(2)
    afa.FeeMonthBox().click()
    time.sleep(1)
    afa.ClickFeeMonth().click()
    time.sleep(1)
    afa.ClickFeeMonth1().click()
    time.sleep(1)
    afa.ClickCurrAdjustmentBox().click()
    time.sleep(1)
    afa.ClickCurrAdjustment1().clear()
    afa.ClickCurrAdjustment1().send_keys(ClickCurrAdjustment1)
    logger.info(u'输入的调整金额是：%s' % ClickCurrAdjustment1)
    afa.ClickAddButton().click()
    time.sleep(1)
    logger.info(u'提示信息：% s' %(afa.information()))

if __name__ == '__main__':
    driver = webdriver.Chrome()
    driver.maximize_window()
    driver.get('http://192.168.1.136:7088/')
    login(driver, 'superadmin', 'superadmin')
    addAdustmentFeeModule(driver, ChooseMerchantDate='李宁', SearchContract='XCSD181017001', SearchAccount='201804', ClickFeeSear='固定租金A', ClickCurrAdjustment1='300')

