'''
封装收款维护独立功能
'''


from PageObject.addCollectionPage import *
from PageObject.tableDataPage import *
from toolKit.log import *
from toolKit.highLightElement import *



def addCollection(driver, merchantName='', contractName='', paymentTime='', settlementGroup='', billNum='', collectionMoney='', deductMoney=''):
	acp = AddCollectionPage(driver)
	logger.info(u'测试收款维护')
	acp.financialManagement().click()
	logger.info(u'点击财务管理')
	acp.collectionManagement().click()
	logger.info(u'点击收款管理')
	acp.collectionMaintain().click()
	logger.info(u'点击收款维护')
	time.sleep(4)
	driver.switch_to.frame(acp.frameOfCollectionMaintain())
	highLightElement(driver, acp.add())
	acp.add().click()
	time.sleep(4)
	logger.info(u'点击添加按钮')
	driver.switch_to.default_content()
	driver.switch_to.frame(acp.frameOfAddCollection())
	highLightElement(driver, acp.merchant())
	acp.merchant().click()
	logger.info(u'点击商户名称文本框')
	highLightElement(driver, acp.merchantInput())
	acp.merchantInput().send_keys(merchantName)
	logger.info(u'输入商户名称：%s' % merchantName)
	highLightElement(driver, acp.merchantSearch())
	acp.merchantSearch().click()
	logger.info(u'点击商户名称搜索按钮')
	time.sleep(1)
	highLightElement(driver, acp.merchantSearchResult())
	acp.merchantSearchResult().click()
	logger.info(u'选择商户名称搜索结果')
	highLightElement(driver, acp.contract())
	acp.contract().click()
	logger.info(u'点击合同号文本框')
	highLightElement(driver, acp.contractInput())
	acp.contractInput().send_keys(contractName)
	logger.info(u'输入合同号：%s' % contractName)
	highLightElement(driver, acp.contractSearch())
	acp.contractSearch().click()
	logger.info(u'点击合同号搜索按钮')
	time.sleep(2)
	highLightElement(driver, acp.contractSearchResult())
	acp.contractSearchResult().click()
	logger.info(u'选择合同号搜索结果')
	highLightElement(driver, acp.paymentTime())
	acp.paymentTime().clear()
	acp.paymentTime().send_keys(paymentTime)
	logger.info(u'输入收款日期：%s' % paymentTime)
	highLightElement(driver, acp.settlementGroup())
	acp.settlementGroup().click()
	logger.info(u'点击结算组别文本框')
	highLightElement(driver, acp.settlementGroupInput())
	acp.settlementGroupInput().send_keys(settlementGroup)
	logger.info(u'输入结算组别：%s' % settlementGroup)
	highLightElement(driver, acp.settlementGroupSearch())
	acp.settlementGroupSearch().click()
	logger.info(u'点击结算组别搜索按钮')
	highLightElement(driver, acp.settlementGroupResult())
	acp.settlementGroupResult().click()
	logger.info(u'选择结算组别搜索结果')
	highLightElement(driver, acp.billNum())
	acp.billNum().click()
	logger.info(u'点击账单号文本框')
	acp.billNumInput().send_keys(billNum)
	logger.info(u'输入账单号：%s' % billNum)
	highLightElement(driver, acp.billNumSearch())
	acp.billNumSearch().click()
	logger.info(u'点击账单号搜索按钮')
	highLightElement(driver, acp.billNumSearchResult())
	acp.billNumSearchResult().click()
	logger.info(u'选择账单号搜索结果')
	acp.costItem().click()
	highLightElement(driver, acp.addRow())
	acp.addRow().click()
	logger.info(u'点击增加行按钮')
	highLightElement(driver, acp.collectionTypeBox())
	acp.collectionTypeBox().click()
	logger.info(u'点击收款方式文本框')
	acp.collectionTypeBoxInner().click()
	acp.collectionType().click()
	logger.info(u'选择收款方式')
	highLightElement(driver, acp.collectionMoneyBox())
	acp.collectionMoneyBox().click()
	logger.info(u'点击收款金额文本框')
	acp.collectionMoney().clear()
	acp.collectionMoney().send_keys(collectionMoney)
	time.sleep(1)
	logger.info(u'输入收款金额：%s' % collectionMoney)
	highLightElement(driver, acp.deductMoneyBox())
	acp.deductMoneyBox().click()
	logger.info(u'点击本次抵扣金额文本框')
	acp.deductMoney().clear()
	acp.deductMoney().send_keys(deductMoney)
	logger.info(u'输入抵扣金额：%s' % deductMoney)
	highLightElement(driver, acp.save())
	acp.save().click()
	logger.info(u'点击保存按钮')
	highLightElement(driver, acp.confirm())
	acp.confirm().click()
	logger.info(u'确认收款信息')
	logger.info(u'提示信息：%s' % (acp.information()))

def addCollectionList(driver, contractName=''):
	acp = AddCollectionPage(driver)
	driver.switch_to.default_content()
	driver.switch_to.frame(acp.frameOfCollectionMaintain())
	time.sleep(3)
	highLightElement(driver, acp.contractOfList())
	acp.contractOfList().click()
	highLightElement(driver, acp.contractInputOfList())
	acp.contractInputOfList().send_keys(contractName)
	highLightElement(driver, acp.contractSearchOfList())
	acp.contractSearchOfList().click()
	highLightElement(driver, acp.contractSearchResultOfList())
	acp.contractSearchResultOfList().click()
	highLightElement(driver, acp.collectionTypeBoxOfList())
	acp.collectionTypeBoxOfList().click()
	highLightElement(driver, acp.collectionTypeOfList())
	acp.collectionTypeOfList().click()
	highLightElement(driver, acp.search())
	acp.search().click()
	gtd = GetTableData(driver)
	fileName = listData + 'addCollectionList.log'
	table = PrettyTable(['购物中心', '收款单编号', '类别', '状态', '经营商户', '经营店铺', '合同号', '账单号', '收款金额', '未收款金额', '是否产生滞纳金', '收款时间'])
	table.align['购物中心'] = '1'
	table.padding_width = 1
	table.add_row([gtd.row14(), gtd.row15(), gtd.row16(), gtd.row17(), gtd.row18(), gtd.row19(), gtd.row110(), gtd.row111(), gtd.row112(), gtd.row113(), gtd.row114(), gtd.row115()])
	logger.info(u'正在获取列表数据')
	time.sleep(1)
	print(table)
	with open(fileName, 'w') as file:
		file.write(str(table))
	logger.info(u'保存位置:%s' % fileName)

