'''
封装滞纳金收款独立功能
'''

from selenium import webdriver
from PageObject.addLateFeeCollectionPage import *
from PageObject.tableDataPage import *
from toolKit.log import *
from toolKit.highLightElement import *



def addLateFeeCollection(driver, merchantName='', contractName='', lateFeeNum='', paymentTime='',  collectionMoney='', deductMoney=''):
	alfcp = AddLateFeeCollectionPage(driver)
	logger.info(u'测试滞纳金收款')
	alfcp.financialManagement().click()
	logger.info(u'点击财务管理')
	alfcp.lateFeeManagement().click()
	logger.info(u'点击滞纳金管理')
	alfcp.lateFeeCollection().click()
	logger.info(u'点击滞纳金收款')
	time.sleep(4)
	driver.switch_to.frame(alfcp.frameOfLateFeeCollection())
	highLightElement(driver, alfcp.add())
	alfcp.add().click()
	time.sleep(4)
	logger.info(u'点击添加按钮')
	driver.switch_to.default_content()
	driver.switch_to.frame(alfcp.frameOfAddLateFeeCollection())
	highLightElement(driver, alfcp.merchant())
	alfcp.merchant().click()
	logger.info(u'点击商户名称文本框')
	highLightElement(driver, alfcp.merchantInput())
	alfcp.merchantInput().send_keys(merchantName)
	logger.info(u'输入商户名称：%s' % merchantName)
	highLightElement(driver, alfcp.merchantSearch())
	alfcp.merchantSearch().click()
	logger.info(u'点击商户名称搜索按钮')
	highLightElement(driver, alfcp.merchantSearchResult())
	alfcp.merchantSearchResult().click()
	logger.info(u'选择商户名称搜索结果')
	highLightElement(driver, alfcp.contract())
	alfcp.contract().click()
	logger.info(u'点击合同号文本框')
	highLightElement(driver, alfcp.contractInput())
	alfcp.contractInput().send_keys(contractName)
	logger.info(u'输入合同号：%s' % contractName)
	highLightElement(driver, alfcp.contractSearch())
	alfcp.contractSearch().click()
	logger.info(u'点击合同号搜索按钮')
	time.sleep(2)
	highLightElement(driver, alfcp.contractSearchResult())
	alfcp.contractSearchResult().click()
	logger.info(u'选择合同号搜索结果')
	highLightElement(driver, alfcp.lateFeeNum())
	alfcp.lateFeeNum().click()
	logger.info(u'点击滞纳金单号文本框')
	highLightElement(driver, alfcp.lateFeeNumInput())
	alfcp.lateFeeNumInput().send_keys(lateFeeNum)
	logger.info(u'输入滞纳金单号：%s' % lateFeeNum)
	highLightElement(driver, alfcp.lateFeeSearch())
	alfcp.lateFeeSearch().click()
	logger.info(u'点击滞纳金单号搜索按钮')
	highLightElement(driver, alfcp.lateFeeSearchResult())
	alfcp.lateFeeSearchResult().click()
	logger.info(u'选择滞纳金单号搜索结果')
	highLightElement(driver, alfcp.paymentTime())
	alfcp.paymentTime().clear()
	alfcp.paymentTime().send_keys(paymentTime)
	logger.info(u'输入收款日期：%s' % paymentTime)
	highLightElement(driver, alfcp.feeType())
	alfcp.feeType().click()
	logger.info(u'点击费用状态文本框')
	highLightElement(driver, alfcp.feeTypeSelect1())
	alfcp.feeTypeSelect1().click()
	logger.info(u'选择费用状态')
	highLightElement(driver, alfcp.addRow())
	alfcp.addRow().click()
	logger.info(u'点击增加行按钮')
	highLightElement(driver, alfcp.collectionTypeBox())
	alfcp.collectionTypeBox().click()
	logger.info(u'点击收款方式文本框')
	alfcp.collectionTypeBoxInner().click()
	alfcp.collectionType().click()
	logger.info(u'选择收款方式')
	highLightElement(driver, alfcp.collectionMoneyBox())
	alfcp.collectionMoneyBox().click()
	logger.info(u'点击收款金额文本框')
	alfcp.collectionMoney().clear()
	alfcp.collectionMoney().send_keys(collectionMoney)
	logger.info(u'输入收款金额：%s' % collectionMoney)
	highLightElement(driver, alfcp.deductMoneyBox())
	alfcp.deductMoneyBox().click()
	logger.info(u'点击本次抵扣金额文本框')
	alfcp.deductMoney().clear()
	alfcp.deductMoney().send_keys(deductMoney)
	logger.info(u'输入抵扣金额：%s' % deductMoney)
	highLightElement(driver, alfcp.save())
	alfcp.save().click()
	logger.info(u'点击保存按钮')
	highLightElement(driver, alfcp.confirm())
	alfcp.confirm().click()
	logger.info(u'确认收款信息')
	logger.info(u'提示信息：%s' % (alfcp.information()))

def addLateFeeCollectionList(driver, contractName=''):
	alfcp = AddLateFeeCollectionPage(driver)
	driver.switch_to.default_content()
	driver.switch_to.frame(alfcp.frameOfLateFeeCollection())
	time.sleep(3)
	highLightElement(driver, alfcp.contractOfList())
	alfcp.contractOfList().click()
	highLightElement(driver, alfcp.contractInputOfList())
	alfcp.contractInputOfList().send_keys(contractName)
	highLightElement(driver, alfcp.contractSearchOfList())
	alfcp.contractSearchOfList().click()
	highLightElement(driver, alfcp.contractSearchResultOfList())
	alfcp.contractSearchResultOfList().click()
	highLightElement(driver, alfcp.search())
	alfcp.search().click()
	time.sleep(2)
	gtd = GetTableData(driver)
	fileName = listData + 'addLateFeeCollectionList.log'
	table = PrettyTable(['购物中心', '状态', '经营商户', '经营店铺', '合同号', '滞纳金单号', '收款金额', '抵扣金额', '未收款金额', '收款时间'])
	table.align['购物中心'] = '1'
	table.padding_width = 1
	table.add_row([gtd.row14(), gtd.row16(), gtd.row17(), gtd.row18(), gtd.row19(), gtd.row110(), gtd.row111(), gtd.row112(), gtd.row113(), gtd.row114()])
	logger.info(u'正在获取列表数据')
	time.sleep(2)
	print(table)
	with open(fileName, 'w') as file:
		file.write(str(table))
	logger.info(u'保存位置:%s' % fileName)
